CREATE SEQUENCE  "OL_INBOUND"."SEQ_AFCS_ENR_TRANS_REF_KEY"  
START WITH 1
INCREMENT BY 1 
MAXVALUE 99999999999999999999
CYCLE ;
CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE" (
AS_OF_DATE	VARCHAR2(20),
EFFECTIVE_DATE	VARCHAR2(20),
ContractId	VARCHAR2(100),
Contractid_type	VARCHAR2(60),
LEGAL_ENTITY	VARCHAR2(60),
GENERAL_LEDGER_ACCOUNT	VARCHAR2(60),
GENERAL_LEDGER_TYPE	VARCHAR2(60),
PRODUCT	VARCHAR2(60),
FINREP_SECTOR	VARCHAR2(60),
ORGANISATION_UNIT	VARCHAR2(60),
INTERCOMPANY	VARCHAR2(60),
SOURCE	VARCHAR2(60),
ANALYSIS	VARCHAR2(60),
Source_Reference	VARCHAR2(60),
Source_Reference_Type	VARCHAR2(60),
Folder	VARCHAR2(60),
Division	VARCHAR2(60),
Counter_Party_ID	VARCHAR2(60),
CounterParty_Description	VARCHAR2(255),
CounterParty_Folder VARCHAR2(60),
Hedge_ID	VARCHAR2(60),
Structure_ID	VARCHAR2(60),
Nostro_ID	VARCHAR2(60),
Nostro_Description	VARCHAR2(255),
RIG_ID	VARCHAR2(60),
Trade_System	VARCHAR2(60),
Maturity_date VARCHAR2(20),
Trade_Value_Date VARCHAR2(30),
LOCAL_CURRENCY	VARCHAR2(3),
CURRENCY	VARCHAR2(3),
BALANCE	VARCHAR2(30),
BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
DAILY_CREDIT_MOVEMENT	VARCHAR2(30),
DAILY_CREDIT_MOVEMENT_IN_LOCAL_CURRENCY	VARCHAR2(30),
DAILY_DEBIT_MOVEMENT	VARCHAR2(30),
DAILY_DEBIT_MOVEMENT_IN_LOCAL_CURRENCY	VARCHAR2(30),
YEAR_TO_DATE_NET_MOVEMENT	VARCHAR2(30),
YEAR_TO_DATE_NET_MOVEMENT_IN_LOCAL_CURRENCY	VARCHAR2(30),
MONTH_TO_DATE_AVERAGE_BALANCE	VARCHAR2(30),
MONTH_TO_DATE_AVERAGE_BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
MONTH_TO_DATE_BALANCE	VARCHAR2(30),
MONTH_TO_DATE_BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
QUARTER_TO_DATE_AVERAGE_BALANCE	VARCHAR2(30),
QUARTER_TO_DATE_AVERAGE_BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
QUARTER_TO_DATE_BALANCE	VARCHAR2(30),
QUARTER_TO_DATE_BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
YEAR_TO_DATE_AVERAGE_BALANCE	VARCHAR2(30),
YEAR_TO_DATE_AVERAGE_BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
YEAR_TO_DATE_BALANCE	VARCHAR2(30),
YEAR_TO_DATE_BALANCE_IN_LOCAL_CURRENCY	VARCHAR2(30),
MLCCID	VARCHAR2(60),
LEDGER	VARCHAR2(60),
ACCOUNTING_STANDARD_CODE	VARCHAR2(60),
Date_Processed DATE,
LOAD_TIME DATE);
GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE" TO OL_INBOUND;
CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_RAW_HA_MX_VAL"
   (	"RECORD_COUNT_CONTROL" NUMBER(32,0), 
	"RECORD_COUNT_FILE" NUMBER(32,0), 
	"COUNT_CONGRUENCE_FLAG" VARCHAR2(10 BYTE), 
	"DATE_PROCESSED" DATE, 
	"LOAD_USER_ID" VARCHAR2(50 BYTE), 
	"LOAD_TIMESTAMP" DATE
   );
GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_HA_MX_VAL" TO OL_INBOUND;
CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_RAW_HA_MX_CTR" 
(	"RECORD_COUNT" NUMBER(32,0), 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"DATE_PROCESSED" DATE, 
	"LOAD_USER_ID" VARCHAR2(20 BYTE), 
	"LOAD_TIMESTAMP" DATE
   );
   GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_HA_MX_CTR" TO OL_INBOUND;
  CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE_CTR" 
(	"RECORD_COUNT" NUMBER(32,0), 
	"FILE_NAME" VARCHAR2(50 BYTE), 
	"DATE_PROCESSED" DATE, 
	"LOAD_USER_ID" VARCHAR2(20 BYTE), 
	"LOAD_TIMESTAMP" DATE
   );
   GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE_CTR" TO OL_INBOUND;
   CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE_VAL"
   (	"RECORD_COUNT_CONTROL" NUMBER(32,0), 
	"RECORD_COUNT_FILE" NUMBER(32,0), 
	"COUNT_CONGRUENCE_FLAG" VARCHAR2(10 BYTE), 
	"DATE_PROCESSED" DATE, 
	"LOAD_USER_ID" VARCHAR2(50 BYTE), 
	"LOAD_TIMESTAMP" DATE
   );
   GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE_VAL" TO OL_INBOUND;
    CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_ENR_BALANCE_CTR" 
   (	"RECORD_COUNT" NUMBER, 
	"DATE_PROCESSED" DATE, 
	"LOAD_USER_ID" VARCHAR2(50 BYTE), 
	"LOAD_TIMESTAMP" DATE
   );
    GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_ENR_BALANCE_CTR" TO OL_INBOUND;
CREATE TABLE "OL_OUTBOUND"."AFCS_STG_HA_MX_BALANCE" (
sequence_number number(32,0),
AsOfDate	date,
EFFECTIVE_DATE	date,
TRADE_VALUE_DATE              	date,
Legal_Entity_Code	varchar2(60),
General_Ledger_Account_Code	varchar2(60),
Product_Code	varchar2(60),
SUK_FINREP_Sector_Code	varchar2(60),
SUK_Intercompany_Code	varchar2(60),
SUK_Cost_Centre_code	varchar2(60),
SUK_Analysis_Code	varchar2(60),
SUK_Source_System_Code	varchar2(60),
Contract_ID	varchar2(100),
Contract_ID_type	varchar2(60),
SUK_Division	varchar2(60),
SUK_Folder	varchar2(60),
SUK_Source_Reference	varchar2(60),
SUK_Source_Reference_type	varchar2(60),
SUK_Nostro_ID	varchar2(60),
SUK_Hedge_ID	varchar2(60),
SUK_Counterparty_ID	varchar2(60),
SUK_Counterparty_Description	varchar2(255),
SUK_Counterparty_folder	varchar2(60),
SUK_Structure_ID	varchar2(60),
SUK_Trade_System	varchar2(60),
SUK_RIG_ID	varchar2(60),
SUK_Maturity_Date	date,
EnteredCurrencyCode	varchar2(3),
Accounting_Balance_In_Entered_Currency	number(22,3),
Functional_Currency_Code	varchar2(3),
Accounting_Balance_In_Functional_Currency	number(22,3),
MLCCID	VARCHAR2(60),
Date_Processed DATE,
LOAD_USER_ID varchar2(60),
LOAD_TIME DATE,
CONSTRAINT "AFCS_STG_HA_MX_BALANCE" PRIMARY KEY (sequence_number,DATE_PROCESSED));
 GRANT ALL ON "OL_OUTBOUND"."AFCS_STG_HA_MX_BALANCE" TO OL_INBOUND;
CREATE TABLE "OL_OUTBOUND"."AFCS_TREASURY_ENR_BALANCE" (
sequence_number number(32,0),
AS_OF_DATE	DATE,
EFFECTIVE_DATE	DATE,
Contract_id 	VARCHAR2(100),
Contractid_type	VARCHAR2(60),
Account_Group	VARCHAR2(3),
Account_Group_desc	VARCHAR2(255),
LEGAL_ENTITY	VARCHAR2(60),
GENERAL_LEDGER_ACCOUNT	VARCHAR2(60),
GENERAL_LEDGER_TYPE	VARCHAR2(60),
PRODUCT	VARCHAR2(60),
FINREP_SECTOR	VARCHAR2(60),
ORGANISATION_UNIT	VARCHAR2(60),
INTERCOMPANY	VARCHAR2(60),
SOURCE	VARCHAR2(60),
ANALYSIS	VARCHAR2(60),
Source_Reference	VARCHAR2(60),
Source_Reference_Type	VARCHAR2(60),
Folder	VARCHAR2(60),
Division	VARCHAR2(60),
CounterParty_ID	VARCHAR2(60),
CounterParty_Description	VARCHAR2(255),
CounterParty_Folder VARCHAR2(60),
Hedge_ID	VARCHAR2(60),
Structure_ID	VARCHAR2(60),
Nostro_ID	VARCHAR2(60),
Nostro_Description	VARCHAR2(255),
FCCS_Entity_Code VARCHAR2(60),
FCCS_Account	VARCHAR2(60),
FCCS_Account_desc	VARCHAR2(255),
RIG_ID	VARCHAR2(60),
Trade_System	VARCHAR2(60),
Maturity_date	DATE,
Trade_Value_Date	DATE,
LOCAL_CURRENCY	VARCHAR2(3),
CURRENCY	VARCHAR2(3),
BALANCE	Number(22,3),
BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
DAILY_CREDIT_MOVEMENT	Number(22,3),
DAILY_CREDIT_MOVEMENT_IN_LOCAL_CURRENCY	Number(22,3),
DAILY_DEBIT_MOVEMENT	Number(22,3),
DAILY_DEBIT_MOVEMENT_IN_LOCAL_CURRENCY	Number(22,3),
YEAR_TO_DATE_NET_MOVEMENT	Number(22,3),
YEAR_TO_DATE_NET_MOVEMENT_IN_LOCAL_CURRENCY	Number(22,3),
MONTH_TO_DATE_AVERAGE_BALANCE	Number(22,3),
MONTH_TO_DATE_AVERAGE_BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
MONTH_TO_DATE_BALANCE	Number(22,3),
MONTH_TO_DATE_BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
QUARTER_TO_DATE_AVERAGE_BALANCE	Number(22,3),
QUARTER_TO_DATE_AVERAGE_BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
QUARTER_TO_DATE_BALANCE	Number(22,3),
QUARTER_TO_DATE_BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
YEAR_TO_DATE_AVERAGE_BALANCE	Number(22,3),
YEAR_TO_DATE_AVERAGE_BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
YEAR_TO_DATE_BALANCE	Number(22,3),
YEAR_TO_DATE_BALANCE_IN_LOCAL_CURRENCY	Number(22,3),
MLCCID	VARCHAR2(255),
LEDGER	VARCHAR2(60),
ACCOUNTING_STANDARD_CODE	VARCHAR2(60),
Date_Processed	DATE ,
LOAD_USER_ID varchar2(60),
LOAD_TIME DATE,
CONSTRAINT "AFCS_TREASURY_ENR_BALANCE" PRIMARY KEY (sequence_number,DATE_PROCESSED) );
GRANT ALL ON "OL_OUTBOUND"."AFCS_TREASURY_ENR_BALANCE" TO OL_INBOUND;
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_HA_MX_VAL" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_HA_MX_CTR" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE_CTR" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_RAW_BALANCE_VAL" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_STG_HA_MX_BALANCE" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_ENR_BALANCE" TO "OL_OUTBOUND_READ_ONLY_ROLE";
GRANT SELECT ON "OL_OUTBOUND"."AFCS_TREASURY_ENR_BALANCE_CTR" TO "OL_OUTBOUND_READ_ONLY_ROLE";